version: '3.8'

services:
  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - minio
    networks:
      - backend

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blazoruser
      POSTGRES_PASSWORD: blazorpass
      POSTGRES_DB: blazordb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - miniodata:/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - blazorapp
      - minio
    networks:
      - backend

volumes:
  pgdata:
  miniodata:

networks:
  backend:
