services:
  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=${DATABASE_NAME};Username=postgres;Password=${DATABASE_PASSWORD}"
      ConnectionStrings__RedisCacheConnection: redis
      ObjectStorage__Endpoint: minio
      ObjectStorage__AccessKey: ${OBJECT_STORAGE_ACCESS_KEY}
      ObjectStorage__SecretKey: ${OBJECT_STORAGE_SECRET_KEY}
    volumes:
      - vaultvids:/vaultvid
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - backend

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${OBJECT_STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${OBJECT_STORAGE_SECRET_KEY}
    volumes:
      - miniodata:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  miniodata:
  redis-data:
  rabbitmq-data:
  vaultvids:

networks:
  backend:
