services:
  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ReddisCacheConnection: redis
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - backend

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: blazoruser
      POSTGRES_PASSWORD: blazorpass
      POSTGRES_DB: blazordb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - miniodata:/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - blazorapp
      - minio
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  miniodata:
  redis-data:

networks:
  backend:
